apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: real-estate
  template:
    metadata:
      labels:
        app: real-estate
    spec:
      containers:
        - name: real-estate-container
          image: y7ksh/real-estate-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "dynamodb.us-east-1.amazonaws.com"
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY

